#!/usr/bin/env python3
"""hookpack — a zero-dependency git hooks manager.

Install declarative hooks into a repository. hookpack never touches a hook
file it did not create: every file it manages carries a '# hookpack:managed'
marker, and any pre-existing file without that marker is left alone.

Stdlib only. Python 3.12+.
"""

from __future__ import annotations

import argparse
import os
import re
import stat
import subprocess
import sys
from pathlib import Path

MARKER = "# hookpack:managed"
TOOL_NAME = "hookpack"
SECRETGATE_URL = (
    "https://raw.githubusercontent.com/tianzhicdev/secretgate/main/secretgate.py"
)

# ---------------------------------------------------------------------------
# Hook registry
# ---------------------------------------------------------------------------
# Each hook declares: the git event it runs on, a human description, and a
# bash body template. Templates are formatted with repo-derived paths.

HOOKS: dict[str, dict] = {
    "secretscan": {
        "event": "pre-commit",
        "description": "Scan the repo for secrets with the secretgate scanner.",
        "template": r"""set -u
top="$(git rev-parse --show-toplevel)" || top="."
cache="__CACHE_DIR__"
if [ -f "$top/secretgate.py" ]; then
  exec python3 "$top/secretgate.py" scan "$top"
fi
if [ -f "$cache/secretgate.py" ]; then
  exec python3 "$cache/secretgate.py" scan "$top"
fi
mkdir -p "$cache" 2>/dev/null || true
if command -v curl >/dev/null 2>&1; then
  if curl -fsSL --max-time 15 -o "$cache/secretgate.py.tmp" "__URL__" 2>/dev/null; then
    mv -f "$cache/secretgate.py.tmp" "$cache/secretgate.py"
    exec python3 "$cache/secretgate.py" scan "$top"
  fi
  rm -f "$cache/secretgate.py.tmp" 2>/dev/null || true
fi
echo "hookpack[secretscan]: secretgate unavailable (no local copy, download failed); skipping scan" >&2
exit 0
""",
    },
    "trimtrail": {
        "event": "pre-commit",
        "description": "Strip trailing whitespace from staged text files.",
        "template": r"""set -u
top="$(git rev-parse --show-toplevel)" || exit 0
cd "$top" || exit 0
git diff --cached --name-only -z 2>/dev/null \
| while IFS= read -r -d '' f; do
    [ -f "$f" ] || continue
    if LC_ALL=C grep -q '[[:space:]]$' "$f" 2>/dev/null && LC_ALL=C grep -Iq . "$f" 2>/dev/null; then
      sed -i -e 's/[[:space:]]*$//' "$f" 2>/dev/null || continue
      git add -- "$f" 2>/dev/null || true
      echo "hookpack[trimtrail]: stripped trailing whitespace in $f"
    fi
  done
exit 0
""",
    },
}

DISPATCHER_TEMPLATE = r"""#!/usr/bin/env bash
{marker}
# Generated by hookpack. Do not edit by hand.
# Re-generate or remove via: hookpack remove <name>
status=0
for h in "{hooks_dir}"/*.hook; do
  [ -e "$h" ] || continue
  case "$(basename "$h")" in
__CASES__
    *) continue ;;
  esac
  if [ -x "$h" ]; then
    "$h" "$@" || status=$?
  else
    bash "$h" "$@" || status=$?
  fi
done
exit $status
"""


# ---------------------------------------------------------------------------
# Git / path plumbing
# ---------------------------------------------------------------------------

class ToolError(Exception):
    """Fatal, user-facing error. Exits with code 1."""


def die(msg: str) -> None:
    print(f"{TOOL_NAME}: error: {msg}", file=sys.stderr)
    sys.exit(1)


def git_dir(work_dir: Path) -> Path:
    """Resolve the git directory for a work tree (supports linked worktrees)."""
    if not work_dir.is_dir():
        raise ToolError(f"work dir does not exist: {work_dir}")
    try:
        r = subprocess.run(
            ["git", "-C", str(work_dir), "rev-parse", "--absolute-git-dir"],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        raise ToolError("git not found on PATH")
    if r.returncode != 0:
        raise ToolError(f"not a git repository: {work_dir}")
    return Path(r.stdout.strip())


def hooks_dir(gd: Path, work_dir: Path) -> Path:
    """Resolve the hooks directory via `git rev-parse --git-path hooks`."""
    r = subprocess.run(
        ["git", "-C", str(work_dir), "rev-parse", "--git-path", "hooks"],
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        raise ToolError("could not resolve git hooks path")
    p = Path(r.stdout.strip())
    # `git rev-parse --git-path hooks` prints a path relative to the work dir
    # (the dir git was invoked in), not to the git dir.
    return p if p.is_absolute() else (work_dir / p).resolve()


def is_managed(path: Path) -> bool:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            return MARKER in fh.read(4096)
    except OSError:
        return False


def mark_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def installed_hooks(gd: Path) -> list[str]:
    hd = gd / "hookpack"
    if not hd.is_dir():
        return []
    return sorted(p.stem for p in hd.glob("*.hook"))


EVENT_RE = re.compile(r"^# hookpack hook: \S+ \(event: (\S+)\)", re.MULTILINE)


def hook_event(name: str, gd: Path) -> str:
    """Event for an installed hook: registry if known, else its header line."""
    if name in HOOKS:
        return HOOKS[name]["event"]
    try:
        m = EVENT_RE.search((gd / "hookpack" / f"{name}.hook").read_text(
            encoding="utf-8", errors="replace"))
        if m:
            return m.group(1)
    except OSError:
        pass
    return "pre-commit"


def render_dispatcher(event: str, gd: Path, installed: list[str]) -> str:
    names = [n for n in installed if hook_event(n, gd) == event]
    cases = "\n".join(
        f"    {n}.hook) ;;  # {n}" for n in sorted(names)
    )
    text = DISPATCHER_TEMPLATE.format(
        marker=MARKER, hooks_dir=str(gd / "hookpack")
    ).replace("__CASES__", cases)
    return text


def sync_dispatchers(gd: Path, hooks_path: Path, work_dir: Path) -> None:
    """Regenerate (or delete) every dispatcher for events backed by hookpack."""
    installed = installed_hooks(gd)
    events = {hook_event(n, gd) for n in installed}
    # also consider dispatchers hookpack already manages
    if hooks_path.is_dir():
        for p in hooks_path.iterdir():
            if p.is_file() and is_managed(p):
                events.add(p.name)
    for event in sorted(events):
        target = hooks_path / event
        names = [n for n in installed if hook_event(n, gd) == event]
        if not names:
            if target.exists() and is_managed(target):
                target.unlink()
                print(f"removed empty dispatcher for '{event}' (no managed hooks left)")
            continue
        if target.exists() and not is_managed(target):
            raise ToolError(
                f"refusing to modify {target}: it does not carry the "
                f"'{MARKER}' marker (hookpack will never touch hooks it did not create)"
            )
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render_dispatcher(event, gd, installed))
        mark_executable(target)


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_add(args: argparse.Namespace) -> int:
    work_dir = Path(args.work_dir).resolve()
    gd = git_dir(work_dir)
    hp = hooks_dir(gd, work_dir)
    name = args.name
    if name not in HOOKS:
        die(f"unknown hook '{name}' (available: {', '.join(sorted(HOOKS))})")
    spec = HOOKS[name]
    target = gd / "hookpack" / f"{name}.hook"
    if target.exists() and not is_managed(target):
        die(f"refusing to overwrite {target}: missing '{MARKER}' marker")

    # Fail before writing anything if the dispatcher slot is occupied by a
    # hook file we did not create.
    dispatcher = hp / spec["event"]
    if dispatcher.exists() and not is_managed(dispatcher):
        die(
            f"refusing to install '{name}': {dispatcher} exists and does not "
            f"carry the '{MARKER}' marker (hookpack will never touch hooks it "
            "did not create); remove or rename it first"
        )

    body = spec["template"].replace("__CACHE_DIR__", str(gd / "hookpack" / "cache")).replace("__URL__", SECRETGATE_URL)
    script = f"#!/usr/bin/env bash\n{MARKER}\n# hookpack hook: {name} (event: {spec['event']})\n{body}"
    (gd / "hookpack").mkdir(parents=True, exist_ok=True)
    target.write_text(script)
    mark_executable(target)
    sync_dispatchers(gd, hp, work_dir)
    print(f"installed '{name}' -> {target} (event: {spec['event']})")
    return 0


def cmd_remove(args: argparse.Namespace) -> int:
    work_dir = Path(args.work_dir).resolve()
    gd = git_dir(work_dir)
    hp = hooks_dir(gd, work_dir)
    name = args.name
    target = gd / "hookpack" / f"{name}.hook"
    if not target.exists():
        die(f"hook '{name}' is not installed")
    if not is_managed(target):
        die(f"refusing to remove {target}: missing '{MARKER}' marker")
    target.unlink()
    sync_dispatchers(gd, hp, work_dir)
    print(f"removed '{name}'")
    return 0


def cmd_list(args: argparse.Namespace) -> int:
    work_dir = Path(args.work_dir).resolve()
    try:
        gd = git_dir(work_dir)
    except ToolError:
        gd = None
    inst = installed_hooks(gd) if gd else []
    print("hookpack hooks:")
    for name in sorted(HOOKS):
        spec = HOOKS[name]
        state = "installed" if name in inst else "not installed"
        print(f"  {name:<12} [{spec['event']}] ({state}) {spec['description']}")
    if gd:
        unknown = [n for n in inst if n not in HOOKS]
        for n in unknown:
            print(f"  {n:<12} [unknown] (installed, not a known hook)")
    return 0


def cmd_doctor(args: argparse.Namespace) -> int:
    work_dir = Path(args.work_dir).resolve()
    gd = git_dir(work_dir)
    hp = hooks_dir(gd, work_dir)
    print(f"repo: {work_dir}")
    print(f"git dir: {gd}")
    print(f"hooks dir: {hp}")
    issues = 0
    if hp.is_dir():
        for p in sorted(hp.iterdir()):
            if not p.is_file() or p.name.endswith(".sample"):
                continue
            if not is_managed(p):
                print(f"  {p.name}: unmanaged hook (left alone by hookpack)")
                continue
            first = p.open("r", encoding="utf-8", errors="replace").readline()
            if not first.startswith("#!"):
                print(f"  {p.name}: ERROR missing shebang line")
                issues += 1
                continue
            if not os.access(p, os.X_OK):
                print(f"  {p.name}: WARN not executable")
                issues += 1
            else:
                print(f"  {p.name}: OK (managed, shebang: {first.strip()})")
    else:
        print("  (hooks dir does not exist yet)")
    for tool in ("git", "python3", "curl", "sed", "grep"):
        found = subprocess.run(["sh", "-c", f"command -v {tool}"],
                               capture_output=True, text=True).stdout.strip()
        print(f"PATH: {tool}: {found if found else 'NOT FOUND'}")
    if issues:
        print(f"doctor: {issues} issue(s) found")
        return 1
    print("doctor: all managed hooks healthy")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="hookpack",
        description="A zero-dependency git hooks manager. "
                    "hookpack only ever touches hooks it created.",
    )
    p.add_argument(
        "--work-dir",
        default=".",
        metavar="DIR",
        help="path to the target git repository (default: current directory)",
    )
    sub = p.add_subparsers(dest="command", required=True)

    a = sub.add_parser("add", help="install a hook (e.g. secretscan, trimtrail)")
    a.add_argument("name", help=f"hook name ({', '.join(sorted(HOOKS))})")
    a.set_defaults(func=cmd_add)

    r = sub.add_parser("remove", help="remove an installed hook")
    r.add_argument("name", help="hook name")
    r.set_defaults(func=cmd_remove)

    l = sub.add_parser("list", help="list available and installed hooks")
    l.set_defaults(func=cmd_list)

    d = sub.add_parser("doctor", help="verify managed hooks, print hook dir, check PATH")
    d.set_defaults(func=cmd_doctor)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return args.func(args)
    except ToolError as e:
        die(str(e))
        return 1  # unreachable


if __name__ == "__main__":
    sys.exit(main())
